"""Minimal password validation API for AAS.

The password itself is not stored in source code. Configure AAS_PASSWORD_HASH
with the value generated by set_password.py, then expose this app through HTTPS.
"""

from __future__ import annotations

import base64
import hashlib
import os
import secrets
import threading
import time
from collections import defaultdict, deque
from typing import Deque

from fastapi import FastAPI, HTTPException, Request, Response
from pydantic import BaseModel, Field

PBKDF2_SCHEME = "pbkdf2_sha256"
MAX_PASSWORD_LENGTH = 256
RATE_LIMIT_ATTEMPTS = int(os.getenv("AAS_RATE_LIMIT_ATTEMPTS", "10"))
RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("AAS_RATE_LIMIT_WINDOW_SECONDS", "60"))
PASSWORD_HASH = os.getenv("AAS_PASSWORD_HASH", "").strip()

if not PASSWORD_HASH:
    raise RuntimeError(
        "AAS_PASSWORD_HASH is not configured. Run set_password.py and export its output."
    )

app = FastAPI(title="AAS Password API", docs_url=None, redoc_url=None)
_attempts: dict[str, Deque[float]] = defaultdict(deque)
_attempts_lock = threading.Lock()


class PasswordRequest(BaseModel):
    password: str = Field(min_length=1, max_length=MAX_PASSWORD_LENGTH)


class PasswordResponse(BaseModel):
    valid: bool


def verify_password(password: str, encoded_hash: str) -> bool:
    """Verify pbkdf2_sha256$iterations$salt_b64$digest_b64."""
    try:
        scheme, iterations_text, salt_text, digest_text = encoded_hash.split("$", 3)
        if scheme != PBKDF2_SCHEME:
            return False
        iterations = int(iterations_text)
        if iterations < 100_000 or iterations > 10_000_000:
            return False
        salt = base64.urlsafe_b64decode(salt_text.encode("ascii"))
        expected = base64.urlsafe_b64decode(digest_text.encode("ascii"))
        actual = hashlib.pbkdf2_hmac(
            "sha256", password.encode("utf-8"), salt, iterations, dklen=len(expected)
        )
        return secrets.compare_digest(actual, expected)
    except (ValueError, TypeError, base64.binascii.Error):
        return False


def client_key(request: Request) -> str:
    # Do not trust X-Forwarded-For unless your reverse proxy overwrites it.
    return request.client.host if request.client else "unknown"


def enforce_rate_limit(key: str) -> None:
    now = time.monotonic()
    cutoff = now - RATE_LIMIT_WINDOW_SECONDS
    with _attempts_lock:
        queue = _attempts[key]
        while queue and queue[0] < cutoff:
            queue.popleft()
        if len(queue) >= RATE_LIMIT_ATTEMPTS:
            raise HTTPException(status_code=429, detail="too many attempts")
        queue.append(now)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/api/check-password", response_model=PasswordResponse)
def check_password(
    payload: PasswordRequest, request: Request, response: Response
) -> PasswordResponse:
    enforce_rate_limit(client_key(request))
    response.headers["Cache-Control"] = "no-store"
    return PasswordResponse(valid=verify_password(payload.password, PASSWORD_HASH))
